use num_derive::{FromPrimitive, ToPrimitive};

#[derive(Debug, FromPrimitive, ToPrimitive, Clone, Copy)]
#[repr(u8)]
pub enum BaseColor {
    None,
    Grass,
    Sand,
    Wool,
    Fire,
    Ice,
    Metal,
    Plant,
    Snow,
    Clay,
    Dirt,
    Stone,
    Water,
    Wood,
    Quartz,
    ColorOrange,
    ColorMagenta,
    ColorLightBlue,
    ColorYellow,
    ColorLightGreen,
    ColorPink,
    ColorGray,
    ColorLightGray,
    ColorCyan,
    ColorPurple,
    ColorBlue,
    ColorBrown,
    ColorGreen,
    ColorRed,
    ColorBlack,
    Gold,
    Diamond,
    Lapis,
    Emerald,
    Podzol,
    Nether,
    TerracottaWhite,
    TerracottaOrange,
    TerracottaMagenta,
    TerracottaLightBlue,
    TerracottaYellow,
    TerracottaLightGreen,
    TerracottaPink,
    TerracottaGray,
    TerracottaLightGray,
    TerracottaCyan,
    TerracottaPurple,
    TerracottaBlue,
    TerracottaBrown,
    TerracottaGreen,
    TerracottaRed,
    TerracottaBlack,
    CrimsonNylium,
    CrimsonStem,
    CrimsonHyphae,
    WarpedNylium,
    WarpedStem,
    WarpedHyphae,
    WarpedWartBlock,
    Deepslate,
    RawIron,
    GlowLichen
}

impl Default for BaseColor {
    fn default() -> Self {
        BaseColor::None
    }
}
